### ISSUE TITLE
"\xE9" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by F-A-L** [pymander/evernote-mode#18]
Sorry for bothering, it's me again(embarrased),  I had googled around, but with no luck, so I ask here again...
Below is the situation:

evernote-open-note  or evernote-browser  is fine;
however, after evernote-create-note or  editing the note from evernote-open-note, evernote-save-note shows
 "\xE9" from ASCII-8BIT to UTF-8. 

the last .evernote-mode.log shows:
E, [2014-11-26T12:06:05.256885 #5251] ERROR -- : ["/usr/bin/enclient.rb:1916:in `eval'", "/usr/bin/enclient.rb:1916:in`run'", "/usr/bin/enclient.rb:1947:in `<main>'"]

I think it's a encoding problem, but have no idea how to debug, please give me some advice, thank you.

**Comment by DiogoFerrari** [comment]
Same issue here. Its anoying. The problem is that some characters are not recognized, like quotation marks. After load a note on emacs buffer, convert to TEXT format, edit and trying to save again, it shows such message. The problem, I guess, is that emacs reads some characters, and saving the note it does not allowed the characters as it were converted into the buffer in the edit mode. Any idea how to fix this?

**Comment by pymander** [comment]
Is there a chance either of you could create a text file that triggers the bug? That would give me a place to start.

**Comment by ryankojima** [comment]
I have similar error too.
I got this error when I'm writing Japanese character.
Here is example text I got error:
あいうえお

I hope it helps to figure out the error

**Comment by ryankojima** [comment]
I fixed the error by changing enclient.rb. It could lead other bugs so at this point I just paste diff here.

diff ~/Downloads/enclient.rb /home/ryan/pkgs/evernote-mode/evernote-mode/ruby/bin/enclient.rb
548,549c548,549
<       Formatter.to_ascii @title, @content, *@tag_names
< 
---
>       Formatter.to_ascii @title,*@tag_names
>       
587,588c587
<       Formatter.to_ascii @title, @notebook_guid, @content, *@tag_names
< 
---
> 	Formatter.to_ascii @title, @notebook_guid, *@tag_names

**Comment by ryankojima** [comment]
I fixed bug by changing enclient.rb. I'm not sure side effect of this so this time I just put diff below

```
548,549c548,549
<       Formatter.to_ascii @title, @content, *@tag_names
< 
---
>       Formatter.to_ascii @title,*@tag_names
>       
587,588c587
<       Formatter.to_ascii @title, @notebook_guid, @content, *@tag_names
< 
---
> 	Formatter.to_ascii @title, @notebook_guid, *@tag_names
```

**Comment by i-takuya** [comment]
I send pull-request to fix this issue.
Please see this pull request.
https://github.com/pymander/evernote-mode/pull/28

**Comment by itsumiken** [comment]
When I try to make any note that has japanese title like "タイトル", I still faced exactly same error.

Thank you.
--
itsumi
